### PR TITLE
Add example and lint

### PR DESCRIPTION
**Pull request by tannewt**

### CODE REVIEW

**Review by makermelissa — APPROVED** [review]
Works great! Thanks.

**Comment by makermelissa** [comment]
I realized there is no display-ruler.bmp in the examples and I used it off the IL0373 PR. Is this something we want to add to the examples?

**Comment by tannewt** [comment]
Ya, I think we want to add it. I'm not sure what the bundle will do with multiple repos bringing in the same file. It'd be ok if they just shared the one.

**Comment by makermelissa** [comment]
Maybe we can add a note into the example file that tells the user where to find it?

**Pull request merged**
